server:
  port: 8081
spring:
  application:
    name: gateway-service
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/merlin-domain
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: gateway-local
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: stories
          uri: http://localhost:8082
          predicates:
            - Path=/stories/**
        - id: httpbin
          uri: http://httpbin.org
          predicates:
            - Path=/httpbin/**
          filters:
            - RewritePath=/httpbin(?<segment>/?.*), $\{segment}
            - AddRequestHeader=Hello2, World2
        - id: baeldung
          uri: http://baeldung.com
          predicates:
            - Path=/baeldung/
          filter:
            - Path
#            - Path=/httpbin/{segment}
#          filters:
logging:
  level:
    org:
      springframework:
        cloud.gateway: DEBUG
        http.server.reactive: DEBUG
        web.reactive: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: gateway